name: metobs_dev_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.8.4=py39h72bdee0_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - astroid=2.15.5=py39hf3d152e_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-lru=2.0.2=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - autopep8=2.0.2=pyhd8ed1ab_0
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.cached-property=1.0.2=pyhd8ed1ab_0
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=23.3.0=py39hf3d152e_1
  - bleach=6.0.0=pyhd8ed1ab_0
  - bqplot=0.12.39=pyhd8ed1ab_0
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cachecontrol=0.12.11=pyhd8ed1ab_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - chardet=5.1.0=py39hf3d152e_0
  - cleo=2.0.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colour=0.1.5=py_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.7=py39h4b4f3f3_0
  - cookiecutter=2.1.1=pyh6c4a22f_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h227be39_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20230430=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - distlib=0.3.6=pyhd8ed1ab_0
  - dnspython=2.2.1=py39h06a4308_0
  - docstring-to-markdown=0.12=pyhd8ed1ab_0
  - docutils=0.16=py39hf3d152e_3
  - dulwich=0.21.5=py39hd1e30aa_0
  - earthengine-api=0.1.354=pyhd8ed1ab_0
  - ee_extra=0.0.15=pyhd8ed1ab_0
  - eerepr=0.0.4=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=4.2.2=h20bf706_0
  - ffmpeg-python=0.2.0=py_0
  - filelock=3.12.0=pyhd8ed1ab_0
  - flake8=6.0.0=pyhd8ed1ab_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - folium=0.14.0=pyhd8ed1ab_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.39.4=py39hd1e30aa_0
  - freetype=2.12.1=hca18f0e_1
  - frozenlist=1.3.3=py39hb9d737c_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdown=4.7.1=pyhd8ed1ab_0
  - geeadd=0.5.6=pyhd8ed1ab_0
  - geemap=0.20.7=pyhd8ed1ab_0
  - geocoder=1.38.1=py_1
  - geojson=3.0.1=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - glib=2.76.3=hfc55251_0
  - glib-tools=2.76.3=hfc55251_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-api-core=2.11.0=pyhd8ed1ab_0
  - google-api-python-client=2.87.0=pyhd8ed1ab_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-storage=2.9.0=pyh1a96a4e_0
  - google-resumable-media=2.5.0=pyhd8ed1ab_0
  - grpcio=1.51.1=py39h712372c_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - html5lib=1.1=pyh9f0ad1d_0
  - httplib2=0.22.0=pyhd8ed1ab_0
  - icu=58.2=hf484d3e_1000
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipyevents=2.0.1=pyhd8ed1ab_0
  - ipyfilechooser=0.6.0=pyhd8ed1ab_0
  - ipykernel=6.23.1=pyh210e3f2_0
  - ipyleaflet=0.17.2=pyhd8ed1ab_0
  - ipython=8.13.2=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipytree=0.2.2=pyhd8ed1ab_0
  - isort=5.12.0=pyhd8ed1ab_1
  - jaraco.classes=3.2.3=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jellyfish=0.9.0=py39hb9d737c_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter-lsp=2.1.0=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py39hf3d152e_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.6.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.0=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.22.1=pyhd8ed1ab_0
  - keyring=23.13.1=py39hf3d152e_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h166bdaf_1003
  - lazy-object-proxy=1.9.0=py39h72bdee0_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=7.88.1=h91b91d3_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=h8f2d780_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.76.3=hebfc3b9_0
  - libgomp=12.2.0=h65d4601_19
  - libgrpc=1.51.1=h05bd8bd_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_2
  - libnghttp2=1.46.0=hce63b2e_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.21.12=h3eb15da_0
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.3=hcbfbd50_0
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.2.13=h166bdaf_4
  - lockfile=0.12.2=py_1
  - logzero=1.7.0=py39hf3d152e_4
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39h72bdee0_0
  - matplotlib=3.7.1=py39hf3d152e_0
  - matplotlib-base=3.7.1=py39he190548_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mdit-py-plugins=0.3.5=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - more-itertools=9.1.0=pyhd8ed1ab_0
  - msgpack-python=1.0.5=py39h4b4f3f3_0
  - multidict=6.0.4=py39h72bdee0_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - myst-parser=1.0.0=pyhd8ed1ab_0
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.4.0=pyhd8ed1ab_0
  - nbconvert-core=7.4.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.4.0=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numpy=1.24.3=py39h6183b62_0
  - numpydoc=1.5.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h0b41bf4_0
  - overrides=7.3.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandoc=2.19.2=h32600fe_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.11.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=pyhd8ed1ab_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - plotly=5.14.1=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - poetry=1.5.0=linux_pyhd8ed1ab_0
  - poetry-core=1.6.0=pyhd8ed1ab_0
  - poetry-plugin-export=1.3.1=pyhd8ed1ab_0
  - proj=9.2.0=h8ffa02c_0
  - prometheus_client=0.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py39h72bdee0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pycrs=1.0.2=py_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.0.1=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pylint=2.17.4=pyhd8ed1ab_0
  - pylint-venv=3.0.1=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqtwebengine=5.15.7=py39h6a678d5_1
  - pyrsistent=0.19.3=py39h72bdee0_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h7a1cb2a_2
  - python-box=7.0.1=py39h72bdee0_0
  - python-build=0.10.0=pyhd8ed1ab_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=1.3.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.0.0=pyhd8ed1ab_0
  - python-lsp-server=1.7.3=pyhd8ed1ab_0
  - python-lsp-server-base=1.7.3=pyhd8ed1ab_0
  - python-slugify=8.0.1=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=25.0.2=py39h0be026e_0
  - qdarkstyle=3.1=pyhd8ed1ab_0
  - qstylizer=0.2.2=pyhd8ed1ab_0
  - qt-main=5.15.2=h8373d8f_8
  - qt-webengine=5.15.9=hbbf29b9_6
  - qtawesome=1.2.3=pyhd8ed1ab_0
  - qtconsole=5.4.3=pyhd8ed1ab_0
  - qtconsole-base=5.4.3=pyha770c72_0
  - qtpy=2.3.1=pyhd8ed1ab_0
  - qtwebkit=5.212=h3fafdc1_5
  - rapidfuzz=2.15.1=py39h227be39_0
  - ratelim=0.1.6=py_2
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rope=1.8.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - rtree=1.0.1=py39hb102c33_1
  - ruamel.yaml=0.17.27=py39hd1e30aa_0
  - ruamel.yaml.clib=0.2.7=py39h72bdee0_1
  - sankee=0.2.3=pyhd8ed1ab_0
  - scooby=0.7.2=pyhd8ed1ab_0
  - secretstorage=3.3.3=py39hf3d152e_1
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=67.7.2=pyhd8ed1ab_0
  - sip=6.6.2=py39h5a03fae_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=5.3.0=pyhd8ed1ab_0
  - sphinx-copybutton=0.5.2=pyhd8ed1ab_0
  - sphinx_rtd_theme=0.4.3=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spyder=5.4.3=py39hf3d152e_0
  - spyder-kernels=2.4.3=unix_pyhd8ed1ab_0
  - sqlite=3.42.0=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyh41d4057_0
  - text-unidecode=1.3=py_0
  - textdistance=4.5.0=pyhd8ed1ab_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.8=pyha770c72_0
  - tornado=6.3.2=py39hd1e30aa_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - ujson=5.7.0=py39h227be39_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - virtualenv=20.23.0=pyhd8ed1ab_0
  - watchdog=3.0.0=py39hf3d152e_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.2=pyhd8ed1ab_0
  - whatthepatch=1.0.5=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - whitebox=2.3.1=pyhd8ed1ab_0
  - whiteboxgui=2.3.0=pyhd8ed1ab_0
  - wrapt=1.15.0=py39h72bdee0_0
  - wurlitzer=3.0.3=pyhd8ed1ab_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.4=h8ee46fc_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2023.5.0=pyhd8ed1ab_1
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yapf=0.33.0=pyhd8ed1ab_1
  - yarl=1.9.1=py39hd1e30aa_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cryptography==40.0.2
      - fiona==1.9.4.post1
      - geopandas==0.9.0
      - google-auth==2.19.0
      - google-crc32c==1.5.0
      - googleapis-common-protos==1.59.0
      - ipywidgets==8.0.6
      - joblib==1.2.0
      - jupyterlab-widgets==3.0.7
      - mapclassify==2.5.0
      - metobs-toolkit==0.1.1a0
      - mysql-connector-python==8.0.33
      - networkx==3.1
      - pandas==1.5.3
      - pillow==9.5.0
      - protobuf==3.20.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyproj==3.4.1
      - pyqt5==5.12.2
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.1
      - scikit-learn==1.2.2
      - scipy==1.9.3
      - shapely==2.0.1
      - shellingham==1.5.0.post1
      - threadpoolctl==3.1.0
      - trove-classifiers==2023.5.24
      - typing-extensions==4.6.2
      - urllib3==1.26.16
      - widgetsnbextension==4.0.7
prefix: /home/thoverga/anaconda3/envs/metobs_dev_env
