name: vlinder_toolkit_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - affine=2.3.1=pyhd8ed1ab_0
  - alabaster=0.7.12=py37_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.2.2=pyhd3eb1b0_0
  - astroid=2.11.7=py37h06a4308_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py37h7deecbd_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py37h27cfd23_1003
  - build=0.7.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.9.24=ha878542_0
  - cairo=1.16.0=h19f5f5c_2
  - cartopy=0.18.0=py37h0d9ca2b_1
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py37h74dc2b5_0
  - cfitsio=3.470=h5893167_7
  - chardet=4.0.0=py37h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=7.1.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=py37h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cmarkgfm=0.8.0=py37h540881e_1
  - colorama=0.4.5=py37h06a4308_0
  - commonmark=0.9.1=py_0
  - contextily=1.2.0=pyhd8ed1ab_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=37.0.1=py37h9ce1e76_0
  - curl=7.84.0=h5eee18b_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - docutils=0.18.1=py37h06a4308_3
  - entrypoints=0.4=py37h06a4308_0
  - expat=2.4.4=h295c915_0
  - fftw=3.3.9=h27cfd23_1
  - fiona=1.8.13.post1=py37hc820daa_0
  - flake8=4.0.1=pyhd3eb1b0_1
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - freexl=1.0.6=h27cfd23_0
  - future=0.18.2=py37h89c1867_5
  - gdal=3.0.2=py37h40f10ac_3
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.9.0=py_1
  - geopandas-base=0.9.0=py_1
  - geoplot=0.5.1=pyhd8ed1ab_0
  - geopy=2.2.0=pyhd8ed1ab_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.7.0=hd69d5b1_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imagesize=1.4.1=py37h06a4308_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - inflection=0.5.1=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.9.1=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py37h06a4308_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=0.9.0=py37h7f8727e_0
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - json-c=0.13.1=h1bed415_0
  - jsonschema=4.4.0=py37h06a4308_0
  - jupyter_client=7.2.2=py37h06a4308_0
  - jupyter_core=4.10.0=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - kealib=1.4.14=hb50703a_1
  - keyring=23.4.0=py37h06a4308_0
  - kiwisolver=1.4.2=py37h295c915_0
  - krb5=1.19.2=hac12032_0
  - lazy-object-proxy=1.6.0=py37h27cfd23_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libclang=10.0.1=default_hb85057a_2
  - libcurl=7.84.0=h91b91d3_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgdal=3.0.2=h1d2d1f6_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libkml=1.3.0=h7ecb851_5
  - libllvm10=10.0.1=hbcb73fb_5
  - libnetcdf=4.8.1=h42ceab0_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.6.0=hdbcaa40_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=4.3.0a=hbedb2dc_20
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=h2818925_1
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzip=1.8.0=h5cef20c_0
  - lz4-c=1.9.3=h295c915_1
  - mapclassify=2.4.3=pyhd3eb1b0_0
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib=3.5.2=py37h06a4308_0
  - matplotlib-base=3.5.2=py37hc347a89_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py37h06a4308_2
  - mercantile=1.2.1=pyhd8ed1ab_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - munch=2.5.0=pyhd3eb1b0_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py37h06a4308_1
  - mysql-connector-c=6.1.11=h24aacaa_2
  - mysql-connector-python=8.0.18=py37h9c95fcb_1
  - nbclient=0.5.13=py37h06a4308_0
  - nbconvert=6.4.4=py37h06a4308_0
  - nbformat=5.3.0=py37h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py37h06a4308_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py37h807cd23_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - numpydoc=1.4.0=py37h06a4308_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h8c16a72_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.9.0=py37h06a4308_0
  - pcre=8.45=h295c915_0
  - pep517=0.12.0=py37h89c1867_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=7.2.0=py37h718be6c_2
  - pip=22.2.2=py37h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkginfo=1.8.3=pyhd8ed1ab_0
  - platformdirs=2.4.0=pyhd3eb1b0_0
  - pluggy=1.0.0=py37h06a4308_1
  - ply=3.11=py37_0
  - poppler=0.81.0=h01f5e8b_2
  - poppler-data=0.4.11=h06a4308_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - proj=6.2.1=h05a3930_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.6.0=py37hf484d3e_0
  - psutil=5.9.0=py37h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.14.5=py37h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyproj=2.6.1.post1=py37hb3025e9_1
  - pyqt=5.15.7=py37h6a678d5_1
  - pyqt5-sip=12.11.0=py37h6a678d5_1
  - pyrsistent=0.18.0=py37heee7806_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py37_1
  - python=3.7.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.3.3=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.1=py37h06a4308_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py37h7f8727e_1
  - pyzmq=23.2.0=py37h6a678d5_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.2.2=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - qtwebkit=5.212=h4eab89a_4
  - rasterio=1.2.10=py37h9a6c7ee_0
  - rasterstats=0.17.0=pyhd8ed1ab_0
  - readline=8.1.2=h7f8727e_1
  - readme_renderer=37.2=pyhd8ed1ab_0
  - regex=2022.7.9=py37h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - requests-toolbelt=0.9.1=py_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - rich=12.6.0=pyhd8ed1ab_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py37h06a4308_1
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37h6c91a56_2
  - seaborn-base=0.12.1=pyhd8ed1ab_0
  - secretstorage=3.3.1=py37h06a4308_0
  - setuptools=63.4.1=py37h06a4308_0
  - shapely=1.8.4=py37h81ba7c5_0
  - simplejson=3.17.6=py37h540881e_1
  - sip=6.6.2=py37h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=5.0.2=py37h06a4308_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.2.2=py37h06a4308_1
  - spyder-kernels=2.2.1=py37h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - testpath=0.6.0=py37h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tiledb=2.3.3=h1132f93_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py37h06a4308_0
  - tomlkit=0.11.1=py37h06a4308_0
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - twine=4.0.1=pyhd8ed1ab_1
  - typed-ast=1.4.3=py37h7f8727e_1
  - typing-extensions=4.3.0=py37h06a4308_0
  - typing_extensions=4.3.0=py37h06a4308_0
  - ujson=5.4.0=py37h6a678d5_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.11=py37h06a4308_0
  - watchdog=2.1.6=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py37h5eee18b_0
  - wurlitzer=3.0.2=py37h06a4308_0
  - xerces-c=3.2.3=h780794e_0
  - xyzservices=2022.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py37h06a4308_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - mysql-connector==2.2.9
    - vlinder-toolkit==0.3.7
prefix: /home/thoverga/anaconda3/envs/vlinder_toolkit_env
